apiVersion: batch/v1
kind: Job
metadata:
  name: mlperf-storage-job
spec:
  template:
    spec:
      containers:
        - name: mlperf-storage-job
          image: ghcr.io/cci-moc/storage-benchmarks:main
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /storage/unet3d_data
              name: unet3d-data
            - mountPath: /dev/shm
              name: shm
          resources:
            requests:
              memory: "16Gi"
              cpu: "4"
            limits:
              memory: "16Gi"
              cpu: "4"
          env:
            - name: NUM_SAMPLES
              value: "3500"
            - name: ACCELERATOR_TYPE
              value: "h100"
      restartPolicy: Never
      volumes:
        - name: unet3d-data
          persistentVolumeClaim:
            claimName: mlperf-storage-data
        - name: shm
          emptyDir:
            medium: Memory
  backoffLimit: 4
